### ISSUE TITLE
Published version doesn't match latest master

### ISSUE THREAD

**Issue by sergeichestakov** [sachinraja/codemirror-lang-elixir#2]
Hey @sachinraja!

Looks like the latest version of this package published on NPM 5 months ago doesn't match what's on main at the moment. Specifically, it looks like the published version is still depending on `@codemirror/stream-parser` 0.18.2 which causes some issues when used in an app that depends on CodeMirror packages versioned 0.19+ since there end up being a number of conflicts with the dependencies that CM stream parser pulls in.

Was wondering if you were planning on publishing an update anytime soon with the updated dependencies?

Cheers!

**Comment by sachinraja** [comment]
Hey, just published a new version that moves `@codemirror/stream-parser` to `peerDependencies`.
